### PR TITLE
Make bundle compatible with Symfony 4

### LINKED ISSUE #32: Symfony 4.0.0  compatibility
(PHP7.2, symfony 4.0)

Trying to install but returns the follow error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/dependency-injection v3.4.0
    - Installation request for aws/aws-sdk-php-symfony ^1.3 -> satisfiable by aws/aws-sdk-php-symfony[1.3.0].
    - Conclusion: remove symfony/console v4.0.0
    - Installation request for symfony/dependency-injection (locked at v4.0.0) -> satisfiable by symfony/dependency-injection[v4.0.0].
    - Conclusion: don't install symfony/console v4.0.0
    - aws/aws-sdk-php-symfony 1.3.0 requires symfony/dependency-injection ~2.3|~3.0 -> satisfiable by symfony/dependency-injection[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
- symfony/dependency-injection v2.3.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.15 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.16 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.17 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.18 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.19 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.20 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.21 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.22 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.23 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.24 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.25 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.26 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.27 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.28 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.29 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.30 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.31 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.32 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.33 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.34 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.35 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.36 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.37 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.38 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.39 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.40 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.41 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.42 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.3.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.4.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.5.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.6.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.15 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.16 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.17 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.18 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.19 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.20 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.21 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.22 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.23 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.24 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.25 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.26 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.27 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.28 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.29 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.30 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.31 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.32 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.33 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.34 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.35 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.36 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.37 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.38 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.7.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.15 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.16 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.17 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.18 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.19 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.20 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.21 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.22 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.23 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.24 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.25 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.26 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.27 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.28 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.29 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.30 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.31 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v2.8.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.0.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.1.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.14 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.2.9 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.0 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.1 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.10 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.11 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.12 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.13 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.2 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.3 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.4 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.5 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.6 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.7 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.8 conflicts with symfony/console[v4.0.0].
    - symfony/dependency-injection v3.3.9 conflicts with symfony/console[v4.0.0].
    - Installation request for symfony/console ^4.0 -> satisfiable by symfony/console[v4.0.0].

Installation failed, reverting ./composer.json to its original content.

### PR DESCRIPTION
**Pull request by brianfreytag**
Fixes service definitions to make services explicitly public because they are private by default in Symfony 4.

Resolves #32 
Closes #29

### CODE REVIEW

**Comment by brianfreytag** [comment]
I will check out these failures in 7.1. I did not receive them in 7.2 locally. I will also add checks for 7.2

**Comment by brianfreytag** [comment]
The failing tests from my initial PR were because of the dynamic service creation happening in AwsExtension. There is a test that pulls services from the container, and each and every one of those were breaking or failling. Symfony 4.0 reverses the default privacy of services. In order to get around this, I updated the service definitions to give them public visibility as they're being created.

**Comment by cjunge-work** [comment]
To whomever can do it: Can we please have this merged and a new release done as soon as possible? The versioning issue currently makes using this package with Symfony4 recipes impossible.

**Comment by cjunge-work** [comment]
@trandangtri wrote the recipe for Symfony4, maybe you can help merge this?

**Comment by trandangtri** [comment]
Hi @cjunge-work and @brianfreytag,

I'm not really sure that we truly need to mark all services of AWS as `public as default` or not. But IMHO, I prefer to use dependency injection instead. This increases the container's performance and easy to maintain, debugging, etc.

If dev has a specified reason to access any AWS service directly from the container, they could do it by themselves, via service alias e.g.

Just my 2 cents.

**Comment by cjunge-work** [comment]
@trandangtri I totally agree re. `public as default`. My issue is that the versioning constraints as it stands prevents using the bundle with Symfony 4. I can configure the services manually but would prefer to use the bundle with the recipe.

**Comment by brianfreytag** [comment]
@trandangtri Taking services that were `public as default` and converting them to `private as default` will cause a lot of backward compatibility issues. Since this is a Symfony bundle, we can't really do that with a minor or patch version, so unless simply upgrading to Symfony 4 is going to be a major release version `~2.0`, then I suggest we keep them public. Symfony bundles, imho, should follow the BC rules of the the parent project.

**Comment by brianfreytag** [comment]
@trandangtri Any further thoughts on this?

**Comment by trandangtri** [comment]
CC @jeskew

**Comment by kstich** [comment]
We should keep this bundle in line with Symfony's idioms, which means leaving the change to `private as default`. Now, when Symfony has taken a major version with the change, seems like the right time to take a new major version of this bundle.

The original Travis job with failures [can be found here](https://travis-ci.org/aws/aws-sdk-php-symfony/jobs/317050711).

**Comment by brianfreytag** [comment]
@kstich I'll make the changes, then. When it gets merged, we just need to make sure it gets tagged as 2.0.

**Comment by brianfreytag** [comment]
@kstich The only issue I see is (and the MAIN reason I set them as public is that there is a test called `all_web_services_in_sdk_manifest_should_be_accessible_as_container_services` that checks to make sure that you can pull them from the container. 

This test was added by @jeskew in the initial commit in 2015. 

I would like to get his opinions.

**Comment by jeskew** [comment]
Hi @brianfeytag,

@kstich and I discussed this offline and were swayed by the argument that fetching a service by name from the container is not a symfony best practice. Bumping the major version and updating the test to reflect current symfony idioms and conventions would be preferable to strict backwards compatibility.

**Comment by brianfreytag** [comment]
@jeskew Thank you. I appreciate your feedback. I will undo my changes and remove that test. I'll have it up within the hour.

**Comment by brianfreytag** [comment]
@jeskew @kstich I've pushed up the updates. I modified one of the tests because I felt bad removing so many of them because they all checked that things got pulled correctly from the container, which, obviously, won't work anymore.

Just a reminder that this will need to be tagged at ~2.0 so that we don't break everybody who has been relying on the container.

File: tests/DependencyInjection/ConfigurationTest.php [hunk 1]
```diff
@@ -1,43 +0,0 @@
...
-     * @dataProvider formatProvider
-     *
-     * @param string $format
-     */
-    public function container_should_compile_and_load($format)
-    {
-        $kernel = new AppKernel('test', true, $format);
-        $kernel->boot();
-
-        $this->assertTrue($kernel->getContainer()->has('aws_sdk'));
```
Comment (jeskew) [inline tests/DependencyInjection/ConfigurationTest.php]: Why not just modify this line to make a more idiomatic assertion? The sample configs could declare a public service into which the SDK is injected, and this test could fetch that service and make an assertion about its state.

File: tests/DependencyInjection/AwsExtensionTest.php [hunk 2]
```diff
@@ -60,12 +34,17 @@ public function all_web_services_in_sdk_manifest_should_be_accessible_as_contain
...
         $serviceName,
-        $serviceRegion
+        $serviceRegion,
+        $clientClassName
     ) {
-        $service = $this->container->get($serviceName);
+
+        $this->args['region'] = $serviceRegion;
+
+        $service = new $clientClassName($this->args);
```
Comment (jeskew) [inline tests/DependencyInjection/AwsExtensionTest.php]: I'm not sure this test is still useful. SDK client construction is tested in the SDK -- tests in this package should exercise the integration with Symfony instead of SDK internals.

File: tests/DependencyInjection/AwsExtensionTest.php [hunk 3]
```diff
@@ -12,46 +12,20 @@
...
-    public function all_web_services_in_sdk_manifest_should_be_accessible_as_container_services(
-        $webServiceName,
-        $containerServiceName,
-        $clientClassName
-    ) {
-        $this->assertTrue(
-            $this->container->has($containerServiceName)
-        );
-
-        $service = $this->container->get($containerServiceName);
```
Comment (jeskew) [inline tests/DependencyInjection/AwsExtensionTest.php]: As with the config test below, couldn't this test just be modified to fetch a public service into which a few SDK clients were injected?

**Comment by brianfreytag** [comment]
@jeskew I updated the tests. As for: `sk_config_should_be_passed_directly_to_the_constructor_and_resolved_by_the_sdk`, I simply used the same idea you had for the other ones. I updated some regions for a couple of sdk configurations and tested against the services I injected into my new "TestService" class.

**Comment by brianfreytag** [comment]
@jeskew @kstich @trandangtri 

Can we take a look at this again, please?

File: tests/fixtures/TestService.php [hunk 4]
```diff
@@ -0,0 +1,76 @@
+<?php
+/*
+ * (c) Lee Industrial Contracting
```
Comment (jeskew) [inline tests/fixtures/TestService.php]: I don't think we can accept a contribution with a separate copyright. Would you be OK with removing this doc block and having the file fall under the same license and copyright as the rest of the repository?

Comment (brianfreytag) [reply tests/fixtures/TestService.php]: lol holy crap. That's embarassing. Stupid PHPStorm. I'll take care of that right now.

**Comment by brianfreytag** [comment]
@jeskew stupid auto-populated copyright notice removed.

**Comment by cjunge-work** [comment]
*waits impatiently...* :)

**Comment by kstich** [comment]
[v2.0.0](https://github.com/aws/aws-sdk-php-symfony/releases/tag/v2.0.0) has been released! Thanks!

**Comment by aequasi** [comment]
Thank you!
