### PR TITLE
Inherit AWS_MERGE_CONFIG value from .env files

### LINKED ISSUE #77: Warnings creating ConfigBuilder
Please fill out the sections below to help us address your issue.

### Version of AWS Service Provider for Symfony?
2.2.2

### Version of Symfony (`bin/console --version` in project dir)?

5.3.2

### Version of PHP (`php -v`)?

8.0.7

### What issue did you see?
2.2.2

```text
10:34:40 WARNING   [app] Failed to generate ConfigBuilder for extension Aws\Symfony\DependencyInjection\AwsExtension. ["exception" => LogicException { …},"extensionClass" => "Aws\Symfony\DependencyInjection\AwsExtension"]
```

### Steps to reproduce

```bash
composer req aws/aws-sdk-php-symfony
bin/console cache:clear -v
```

### PR DESCRIPTION
**Pull request by Khez**
Closes #77 

Also invalidates #82

### CODE REVIEW

**Comment by Khez** [comment]
@SamRemis anything blocking this?

File: src/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -117,4 +117,21 @@ public function getConfigTreeBuilder()
...
+        # works with symfony/dotenv
+        if (isset($_ENV['AWS_MERGE_CONFIG'])) {
+            return $_ENV['AWS_MERGE_CONFIG'];
+        }
+
+        # works with case-insensitive names on windows and doesn't work with symfony/dotenv
+        $mergeConfig = getenv('AWS_MERGE_CONFIG');
+
+        if ($mergeConfig) {
+            @trigger_error('Since aws/aws-sdk-php-symfony 2.5.0: Support for case-insensitive AWS_MERGE_CONFIG is deprecated and will be removed in 3.0.0', \E_USER_DEPRECATED);
```
Comment (SamRemis) [inline src/DependencyInjection/Configuration.php:132]: Can you split this into a few lines to conform to PSR line limit standards?  I know that standard is a topic of debate, but it's something we follow in the PHP SDK.
example:
```
@trigger_error(
    'Since aws/aws-sdk-php-symfony 2.5.0: Support for case-insensitive'
    . ' AWS_MERGE_CONFIG is deprecated and will be removed in 3.0.0', 
    \E_USER_DEPRECATED
);
```

**Comment by SamRemis** [comment]
> @SamRemis anything blocking this?

Just commented on the PR.  If you want to discuss the line limit, I'm happy to hear other opinion.  I think in the next version of the SDK I'd like to ignore line limit lengths on error warnings, but for now it's how our code looks.  

If you make the change, I can go ahead and merge/release this

File: src/DependencyInjection/Configuration.php (hunk 1 above)
Comment (SamRemis) [inline src/DependencyInjection/Configuration.php:132]: For posterity, here's a link to a PR that uses this same syntax in the symfony repo:

https://github.com/symfony/symfony/pull/14900/files

Comment (SamRemis) [inline src/DependencyInjection/Configuration.php:132]: For posterity, here's a link to a PR that uses this same syntax in the symfony repo:

https://github.com/symfony/symfony/pull/14900/files

**Comment by Khez** [comment]
Done and done!

The only thing that had me wondering was:
Would it make more sense to change **3.0.0** to **a future release** in the deprecation message ?

Other than that, we're golden!

**Comment by Khez** [comment]
@SamRemis anything else that might be blocking this ?

We're using a composer post install/update hook to apply this exact patch so we don't get any warnings during our pipeline.

But I'd much rather update to `"aws/aws-sdk-php-symfony": "2.5.0"` 😃

**Review by SamRemis — APPROVED** [review]
